version: '3.4'

networks:
  frontend:
  backend:

services:
  catalog:
    image: events/catalogapi
    build:
      context: .\EventCatalogAPI
      dockerfile: Dockerfile
    environment:
      ExternalCatalogBaseUrl: http://localhost:6543
      DatabaseServer: mssqlserver
      DatabaseName: CatalogEventDb
      DatabaseUser: sa 
      DatabasePassword: EventApi(!)
    ports:
      - "6543:80"
    container_name: eventscatalogapi
    networks:
      - frontend
      - backend
    depends_on:
      - mssqlserver
      

  mssqlserver:
    image: "microsoft/mssql-server-linux:latest"
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: EventApi(!)
    ports:
      - "1357:1433"
    container_name: eventssqlserver
    networks:
      - backend