version: '3.4'

networks:
  frontend:
  backend:

services:
  catalog:
    image: events/catalogapi
    build:
      context: .\EventCatalogAPI
      dockerfile: Dockerfile
    environment:
      ExternalCatalogBaseUrl: http://localhost:6543
      DatabaseServer: mssqlserver
      DatabaseName: CatalogEventDb
      DatabaseUser: sa 
      DatabasePassword: EventApi(!)
    ports:
      - "6543:80"
    container_name: eventscatalogapis
    networks:
      - frontend
      - backend
    depends_on:
      - mssqlserver

  webmvc:
    image: events/webmvc
    build:
      context: .\WebMvc
      dockerfile: Dockerfile
    environment:
      CatalogUrl: http://catalog
      CartUrl: http://cart
      ASPNETCORE_ENVIRONMENT: Development
      IdentityUrl: http://192.168.87.65:6750
      CallBackUrl: http://localhost:6818
    ports:
      - "6818:80"
    container_name: onlinewebevent
    networks:
      - frontend
    depends_on:
      - catalog
      - cart
      - tokenserver 
      
  tokenserver:
    build:
      context: .\TokenServiceApi
      dockerfile: Dockerfile
    image: events/tokenapi
    environment:
      Mvcclient: http://localhost:6818
    ports:
      - "6750:80"
    container_name: tokenserviceapis
    networks:
      - backend
      - frontend
    depends_on:
      - mssqlserver

  cart:
    build:
      context: .\CartApi
      dockerfile: Dockerfile
    image: events/cartapi
    environment:
      IdentityUrl: http://192.168.87.65:6750
      ConnectionString: basket.data
    ports:
      - "6817:80"
    container_name: eventcartapi
    networks:
      - backend
      - frontend
    depends_on:
      - tokenserver
      - basket.data


  mssqlserver:
    image: "microsoft/mssql-server-linux:latest"
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: EventApi(!)
    ports:
      - "1357:1433"
    container_name: eventssqlservers
    networks:
      - backend


  basket.data:
    image: redis
    container_name: eventbasketdata
    ports:
      - "6085:6379"
    networks:
      - backend
